In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [11]:
df= pd.read_csv('E:\PGCP -BDA\machine learning\Machine_Learning\Assignments\Datasets./Salaries .csv')
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [13]:
df.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [14]:
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [15]:
df.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [16]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [20]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [64]:

df.select_dtypes(include='number').agg(['max', 'min', 'mean', 'median', 'std'])

              phd    service         salary
max     56.000000  51.000000  186960.000000
min      1.000000   0.000000   57800.000000
mean    19.705128  15.051282  108023.782051
median  18.500000  14.500000  104671.000000
std     12.498425  12.139768   28293.661022

In [28]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [29]:
df.isna().sum()

rank          0
discipline    0
phd           0
service       0
sex           0
salary        0
dtype: int64

In [30]:
df.dropna()

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [38]:
df[df['salary']>50000]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [34]:
df[df['salary']<20000]

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [36]:
df[df['salary'].between(20000,50000)]

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []

In [39]:
df[df['salary']>100000]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
7        Prof          A   18       18    Male  126300
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
65       Prof          A   36       19  Female  117555
69       Prof          A   28        7  Female  116450
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [40]:
df[df['salary']<100000]

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
6   AssocProf          A   20       17    Male   81285
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
12   AsstProf          B    1        0    Male   88000
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
38   AsstProf          B    4        3    Male   91000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
46   AsstProf          B   11        3  Female   74692
50   AsstProf          B   10        5  Female   97032
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
60   AsstProf          B    3        3  Female   92000
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065

In [41]:
df[df['discipline'] == 'A']

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
32       Prof          A   27       19    Male  103275
37       Prof          A   20        8    Male  102000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [42]:
df[df['discipline']=="B"]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
4        Prof          B   20       18    Male  104800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312

In [43]:
df[df['service']>10]

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
54  AssocProf          A   25       22  Female   62884
58       Prof          B   36       26  Female  144651
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
67       Prof          A   17       11  Female   90450
72       Prof          B   24       15  Female  161101
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [44]:
df[df['service']<5]

        rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
15      Prof          B   17        3    Male  150480
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
52      Prof          A   12        0  Female  105000
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500

In [50]:
df[['phd','salary']]

    phd  salary
0    56  186960
1    12   93000
2    23  110515
3    40  131205
4    20  104800
..  ...     ...
73   18  105450
74   19  104542
75   17  124312
76   28  109954
77   23  109646

[78 rows x 2 columns]

In [51]:
df[['rank','sex' ,'salary']]

         rank     sex  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]

In [53]:
df[[ i for i in df.columns if i != 'salary']]

         rank discipline  phd  service     sex
0        Prof          B   56       49    Male
1        Prof          A   12        6    Male
2        Prof          A   23       20    Male
3        Prof          A   40       31    Male
4        Prof          B   20       18    Male
..        ...        ...  ...      ...     ...
73       Prof          B   18       10  Female
74  AssocProf          B   19        6  Female
75       Prof          B   17       17  Female
76       Prof          A   28       14  Female
77       Prof          A   23       15  Female

[78 rows x 5 columns]

In [57]:
df[[ i for i in df.columns if i in ['rank','service','salary']]].head(50)

         rank  service  salary
0        Prof       49  186960
1        Prof        6   93000
2        Prof       20  110515
3        Prof       31  131205
4        Prof       18  104800
5        Prof       20  122400
6   AssocProf       17   81285
7        Prof       18  126300
8        Prof       19   94350
9        Prof       51   57800
10       Prof       33  128250
11       Prof       23  134778
12   AsstProf        0   88000
13       Prof       33  162200
14       Prof       19  153750
15       Prof        3  150480
16   AsstProf        3   75044
17   AsstProf        0   92000
18       Prof        7  107300
19       Prof       27  150500
20   AsstProf        4   92000
21       Prof       30  103106
22   AsstProf        2   73000
23   AsstProf        0   85000
24       Prof       23   91100
25       Prof       31   99418
26       Prof       19  148750
27       Prof       43  155865
28   AsstProf        2   91300
29       Prof       20  123683
30  AssocProf        7  107008
31       Prof       21  155750
32       Prof       19  103275
33       Prof       18  120000
34  AssocProf        8  119800
35       Prof       23  126933
36       Prof       45  146856
37       Prof        8  102000
38   AsstProf        3   91000
39       Prof       18  129000
40       Prof       36  137000
41  AssocProf        8   74830
42   AsstProf        2   80225
43   AsstProf        0   77000
44       Prof       19  151768
45       Prof       25  140096
46   AsstProf        3   74692
47  AssocProf       11  103613
48       Prof       17  111512
49       Prof       18  122960

In [62]:
df[df['rank'] == 'Prof']

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

In [63]:
df[df['rank'] =='AssocProf']

         rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542