In [1]:
import pandas as pd

emp_list = [
    (101, 'Alice'), (102, 'Bob'), (103, 'Charlie'), (104, 'David'), (105, 'Eva'),
    (106, 'Frank'), (107, 'Grace'), (108, 'Henry'), (109, 'Ivy'), (110, 'Jack')
]

emp_series = pd.Series(emp_list)

print(type(emp_series))

df = pd.DataFrame(emp_series.tolist(), columns=['empid', 'name'])
df

<class 'pandas.core.series.Series'>

   empid     name
0    101    Alice
1    102      Bob
2    103  Charlie
3    104    David
4    105      Eva
5    106    Frank
6    107    Grace
7    108    Henry
8    109      Ivy
9    110     Jack

In [2]:
df

   empid     name
0    101    Alice
1    102      Bob
2    103  Charlie
3    104    David
4    105      Eva
5    106    Frank
6    107    Grace
7    108    Henry
8    109      Ivy
9    110     Jack

In [3]:
df.head(5)

   empid     name
0    101    Alice
1    102      Bob
2    103  Charlie
3    104    David
4    105      Eva

In [4]:
df.tail(5)

   empid   name
5    106  Frank
6    107  Grace
7    108  Henry
8    109    Ivy
9    110   Jack

In [5]:
pd.concat([df.head(2), df.tail(2)])

   empid   name
0    101  Alice
1    102    Bob
8    109    Ivy
9    110   Jack

In [6]:
df.loc[4, 'name']

'Eva'

In [7]:
df.iloc[3]

empid      104
name     David
Name: 3, dtype: object