In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sbn

In [6]:
df= pd.read_csv('E:\PGCP -BDA\machine learning\Machine_Learning\Assignments\Datasets./Advertising.csv')
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [7]:
df.tail()

        TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [10]:
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [11]:
df.tail(3)

        TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [14]:
df.dtypes

TV           float64
radio        float64
newspaper    float64
sales        float64
dtype: object

In [17]:
df.isna().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [25]:
df.drop(columns=['radio']).head(10)

      TV  newspaper  sales
0  230.1       69.2   22.1
1   44.5       45.1   10.4
2   17.2       69.3    9.3
3  151.5       58.5   18.5
4  180.8       58.4   12.9
5    8.7       75.0    7.2
6   57.5       23.5   11.8
7  120.2       11.6   13.2
8    8.6        1.0    4.8
9  199.8       21.2   10.6

In [30]:
df['updated_sales']=df['sales']*10
df.head(10)

      TV  radio  newspaper  sales  updated_sales
0  230.1   37.8       69.2   22.1          221.0
1   44.5   39.3       45.1   10.4          104.0
2   17.2   45.9       69.3    9.3           93.0
3  151.5   41.3       58.5   18.5          185.0
4  180.8   10.8       58.4   12.9          129.0
5    8.7   48.9       75.0    7.2           72.0
6   57.5   32.8       23.5   11.8          118.0
7  120.2   19.6       11.6   13.2          132.0
8    8.6    2.1        1.0    4.8           48.0
9  199.8    2.6       21.2   10.6          106.0

In [31]:
df.shape

(200, 5)

In [35]:

df.agg(['max', 'min', 'mean', 'median', 'std'])

                TV      radio   newspaper      sales  updated_sales
max     296.400000  49.600000  114.000000  27.000000     270.000000
min       0.700000   0.000000    0.300000   1.600000      16.000000
mean    147.042500  23.264000   30.554000  14.022500     140.225000
median  149.750000  22.900000   25.750000  12.900000     129.000000
std      85.854236  14.846809   21.778621   5.217457      52.174566

In [33]:
df.describe()

               TV       radio   newspaper       sales  updated_sales
count  200.000000  200.000000  200.000000  200.000000     200.000000
mean   147.042500   23.264000   30.554000   14.022500     140.225000
std     85.854236   14.846809   21.778621    5.217457      52.174566
min      0.700000    0.000000    0.300000    1.600000      16.000000
25%     74.375000    9.975000   12.750000   10.375000     103.750000
50%    149.750000   22.900000   25.750000   12.900000     129.000000
75%    218.825000   36.525000   45.100000   17.400000     174.000000
max    296.400000   49.600000  114.000000   27.000000     270.000000