In [141]:
# Que1.-
# Predict if a person would buy life insurance based on his age using logistic regression.
# About Dataset - Age: Age of a person
# bought_insurance : whether person buys Insurance or not (0 - No, 1 - Yes)
# predict it for Age : 58,30,20,49,53

# Dataset : insurance_data.csv

# Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score,f1 score.

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [71]:
df = pd.read_csv('insurance_data.csv')
df.head(2)

   age  bought_insurance
0   22                 0
1   25                 0

In [72]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   age               27 non-null     int64
 1   bought_insurance  27 non-null     int64
dtypes: int64(2)
memory usage: 564.0 bytes

In [73]:
df.describe()

             age  bought_insurance
count  27.000000         27.000000
mean   39.666667          0.518519
std    15.745573          0.509175
min    18.000000          0.000000
25%    25.000000          0.000000
50%    45.000000          1.000000
75%    54.500000          1.000000
max    62.000000          1.000000

In [74]:
df.corr()

                       age  bought_insurance
age               1.000000          0.732395
bought_insurance  0.732395          1.000000

In [75]:
x = df.drop('bought_insurance', axis = 1)
y = df['bought_insurance']

In [76]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.8,random_state=42)

In [77]:
from sklearn.linear_model import LogisticRegressionCV

model = LogisticRegressionCV()

model.fit(x_train,y_train)

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

LogisticRegressionCV()

In [78]:
y_pred = model.predict(x_test)

In [79]:
print(f"train score = {model.score(x_train, y_train)}")

train score = 0.8571428571428571

In [80]:
print(f"test score = {model.score(x_test, y_test)}")

test score = 1.0

In [81]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         2

    accuracy                           1.00         6
   macro avg       1.00      1.00      1.00         6
weighted avg       1.00      1.00      1.00         6

In [111]:
from sklearn.metrics import confusion_matrix

# calculate confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[4 0]
 [0 2]]

In [114]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"accuracy = {accuracy * 100:.2f}%")

accuracy = 100.00%

In [115]:
from sklearn.metrics import precision_score

precision = precision_score(y_test, y_pred)
print(f"precision = {precision * 100:.2f}%")

precision = 100.00%

In [116]:
from sklearn.metrics import recall_score

recall = recall_score(y_test, y_pred)
print(f"recall = {recall * 100:.2f}%")

recall = 100.00%

In [117]:
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred)
print(f"f1 score = {f1 * 100:.2f}%")

f1 score = 100.00%

In [82]:
print(model.predict([[58]]))

[1]

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegressionCV was fitted with feature names
  warnings.warn(

In [83]:
print(model.predict([[30]]))

[0]

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegressionCV was fitted with feature names
  warnings.warn(

In [84]:
print(model.predict([[20]]))

[0]

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegressionCV was fitted with feature names
  warnings.warn(

In [85]:
print(model.predict([[49]]))

[1]

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegressionCV was fitted with feature names
  warnings.warn(

In [86]:
print(model.predict([[53]]))

[1]

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegressionCV was fitted with feature names
  warnings.warn(

In [140]:
# ######Ques2
# Que2.-
# In this dataset you have to predict that whether we have to give ATTORNEY to the clients or not (0=Yes, 1=No) based on below factors.
# CLMAGE - Age of Client
# CLMSEX - Sex of client (0=Male, 1= Female)
# SEATBELT - Whether client has Seatbelt or not (0=Yes, 1=No)
# CLMINSUR - Whether Client give Insurance or not (0=Yes, 1=No)
# LOSS - Loss that client faced

# Prepare model by using logistic regression & Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.

# Dataset : Claimants.csv

In [88]:
df1 = pd.read_csv('claimants.csv')
df1.head(2)

   ATTORNEY  CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0         0     0.0       1.0       0.0    50.0  34.940
1         1     1.0       0.0       0.0    18.0   0.891

In [89]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ATTORNEY  1340 non-null   int64
 1   CLMSEX    1328 non-null   float64
 2   CLMINSUR  1299 non-null   float64
 3   SEATBELT  1292 non-null   float64
 4   CLMAGE    1151 non-null   float64
 5   LOSS      1340 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 62.9 KB

In [90]:
df1.dropna(inplace=True)

In [91]:
df1.info()

<class 'pandas.DataFrame'>
Index: 1096 entries, 0 to 1339
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ATTORNEY  1096 non-null   int64
 1   CLMSEX    1096 non-null   float64
 2   CLMINSUR  1096 non-null   float64
 3   SEATBELT  1096 non-null   float64
 4   CLMAGE    1096 non-null   float64
 5   LOSS      1096 non-null   float64
dtypes: float64(5), int64(1)
memory usage: 59.9 KB

In [92]:
df1.describe()

,ATTORNEY,CLMSEX,CLMINSUR,SEATBELT,CLMAGE,LOSS
count,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000,1096.000000
mean,0.472628,0.564781,0.904197,0.018248,28.587591,3.856578
std,0.499478,0.496012,0.294455,0.133909,20.392621,10.473239
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,1.000000,0.000000,9.000000,0.440000
50%,0.000000,1.000000,1.000000,0.000000,30.000000,1.311000
75%,1.000000,1.000000,1.000000,0.000000,43.000000,3.910500
max,1.000000,1.000000,1.000000,1.000000,95.000000,173.604000

In [93]:
x1 = df1.drop('ATTORNEY',axis=1)
y1= df1['ATTORNEY']

In [94]:
x1

      CLMSEX  CLMINSUR  SEATBELT  CLMAGE    LOSS
0        0.0       1.0       0.0    50.0  34.940
1        1.0       0.0       0.0    18.0   0.891
2        0.0       1.0       0.0     5.0   0.330
3        0.0       1.0       1.0    31.0   0.037
4        0.0       1.0       0.0    30.0   0.038
...      ...       ...       ...     ...     ...
1334     1.0       1.0       0.0    16.0   0.060
1336     1.0       1.0       0.0    46.0   3.705
1337     1.0       1.0       0.0    39.0   0.099
1338     1.0       0.0       0.0     8.0   3.177
1339     1.0       1.0       0.0    30.0   0.688

[1096 rows x 5 columns]

In [95]:
from sklearn.model_selection import train_test_split

x1_train,x1_test,y1_train,y1_test = train_test_split(x1,y1,train_size=0.8,random_state=42)

In [96]:
from sklearn.linear_model import LogisticRegressionCV

model = LogisticRegressionCV()

model.fit(x1_train,y1_train)

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(

LogisticRegressionCV()

In [97]:
print(f"model score: {model.score(x1_train,y1_train)}")

model score: 0.7146118721461188

In [98]:
print(f"model score: {model.score(x1_test,y1_test)}")

model score: 0.6590909090909091

In [99]:
y1_pred = model.predict(x1_test)

In [128]:
from sklearn.metrics import confusion_matrix

# calculate confusion matrix
cm1 = confusion_matrix(y1_test, y1_pred)
print(cm1)

[[73 38]
 [37 72]]

In [100]:
from sklearn.metrics import classification_report
print(classification_report(y1_test,y1_pred))

              precision    recall  f1-score   support

           0       0.66      0.66      0.66       111
           1       0.65      0.66      0.66       109

    accuracy                           0.66       220
   macro avg       0.66      0.66      0.66       220
weighted avg       0.66      0.66      0.66       220

In [101]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y1_test,y1_pred)
print(f"accuracy : {accuracy*100:.2f}%")

accuracy : 65.91%

In [102]:
from sklearn.metrics import precision_score
precision = precision_score(y1_test,y1_pred)
print(f"precision: {precision *100:.2f}%")

precision: 65.45%

In [103]:
from sklearn.metrics import recall_score
recall  = recall_score(y1_test,y1_pred)
print(f"recall: {recall*100:.2f}%")

recall: 66.06%

In [104]:
from sklearn.metrics import f1_score
f1 = f1_score(y1_test,y1_pred)
print(f"f1 score: {f1 *100:.2f}%")

f1 score: 65.75%

In [105]:
#####Ques3

In [139]:
# ##problem statement
# The model's main purpose is to predict the 10-year risk of Coronary Heart Disease (CHD). CHD is a disease of the blood vessels supplying the heart. Heart disease has been the leading cause of death worldwide since 1921. In 2008, 7.3 million people died from CHD. 
# The classification goal is to predict whether the patient has 10-year risk of future coronary heart disease (CHD).The dataset provides the patients’ information. It includes over 4,000 records and 15 attributes.
# Variables
# Sex: male or female(0=female, 1=male)
# Age: Age of the patient
# education: Some high school (1), high school/GED (2), some college/vocational school (3), college (4)
# Current Smoker: whether or not the patient is a current smoker (0=No, 1=Yes)
# Cigs Per Day: the number of cigarettes that the person smoked on average in one day
# BP Meds: whether or not the patient was on blood pressure medication 
# Prevalent Stroke: whether or not the patient had previously had a stroke (0=No, 1=Yes)
# Prevalent Hyp: whether or not the patient was hypertensive (0=No, 1=Yes)
# Diabetes: whether or not the patient had diabetes (0=No, 1=Yes)
# Tot Chol: total cholesterol level
# Sys BP: systolic blood pressure 
# Dia BP: diastolic blood pressure
# BMI: Body Mass Index
# Heart Rate: heart rate
# Glucose: glucose level

# Prepare model by using logistic regression.

# Also calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.
# Datasets : framingham.csv
# #

In [106]:
df2 = pd.read_csv("framingham.csv")
df2.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [107]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 4240 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             4240 non-null   int64
 1   age              4240 non-null   int64
 2   education        4135 non-null   float64
 3   currentSmoker    4240 non-null   int64
 4   cigsPerDay       4211 non-null   float64
 5   BPMeds           4187 non-null   float64
 6   prevalentStroke  4240 non-null   int64
 7   prevalentHyp     4240 non-null   int64
 8   diabetes         4240 non-null   int64
 9   totChol          4190 non-null   float64
 10  sysBP            4240 non-null   float64
 11  diaBP            4240 non-null   float64
 12  BMI              4221 non-null   float64
 13  heartRate        4239 non-null   float64
 14  glucose          3852 non-null   float64
 15  TenYearCHD       4240 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 530.1 KB

In [108]:
df2.dropna(inplace=True)

In [109]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3658 entries, 0 to 4239
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   male             3658 non-null   int64
 1   age              3658 non-null   int64
 2   education        3658 non-null   float64
 3   currentSmoker    3658 non-null   int64
 4   cigsPerDay       3658 non-null   float64
 5   BPMeds           3658 non-null   float64
 6   prevalentStroke  3658 non-null   int64
 7   prevalentHyp     3658 non-null   int64
 8   diabetes         3658 non-null   int64
 9   totChol          3658 non-null   float64
 10  sysBP            3658 non-null   float64
 11  diaBP            3658 non-null   float64
 12  BMI              3658 non-null   float64
 13  heartRate        3658 non-null   float64
 14  glucose          3658 non-null   float64
 15  TenYearCHD       3658 non-null   int64
dtypes: float64(9), int64(7)
memory usage: 485.8 KB

In [119]:
x2=df2.drop('TenYearCHD',axis=1)
y2=df2['TenYearCHD']

In [143]:
df2.corr()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
male,1.000000,-0.024412,0.017729,0.206114,0.330322,-0.052124,-0.002312,0.001424,0.013819,-0.070321,-0.045358,0.051872,0.073111,-0.115285,0.002940,0.091688
age,-0.024412,1.000000,-0.159499,-0.210771,-0.189295,0.134732,0.050893,0.306239,0.109092,0.268252,0.388267,0.208283,0.137511,-0.002722,0.118349,0.233983
education,0.017729,-0.159499,1.000000,0.025251,0.013790,-0.013739,-0.030386,-0.078828,-0.039627,-0.013522,-0.124360,-0.058059,-0.137555,-0.064214,-0.031998,-0.063279
currentSmoker,0.206114,-0.210771,0.025251,1.000000,0.773913,-0.051923,-0.038150,-0.108078,-0.041849,-0.051034,-0.134428,-0.115955,-0.159821,0.050841,-0.053242,0.019165
cigsPerDay,0.330322,-0.189295,0.013790,0.773913,1.000000,-0.046504,-0.036286,-0.070460,-0.036961,-0.030400,-0.094781,-0.056746,-0.087395,0.064030,-0.053726,0.052014
BPMeds,-0.052124,0.134732,-0.013739,-0.051923,-0.046504,1.000000,0.113125,0.262910,0.049066,0.094083,0.271263,0.199630,0.105642,0.012889,0.054232,0.089152
prevalentStroke,-0.002312,0.050893,-0.030386,-0.038150,-0.036286,0.113125,1.000000,0.066057,0.009625,0.012736,0.061070,0.055834,0.036496,-0.017019,0.016061,0.048366
prevalentHyp,0.001424,0.306239,-0.078828,-0.108078,-0.070460,0.262910,0.066057,1.000000,0.080556,0.166655,0.697675,0.617734,0.302949,0.146818,0.086942,0.181387
diabetes,0.013819,0.109092,-0.039627,-0.041849,-0.036961,0.049066,0.009625,0.080556,1.000000,0.048451,0.102552,0.050686,0.089009,0.060984,0.614820,0.093431
totChol,-0.070321,0.268252,-0.013522,-0.051034,-0.030400,0.094083,0.012736,0.166655,0.048451,1.000000,0.219925,0.174422,0.121056,0.093053,0.049884,0.091338
sysBP,-0.045358,0.388267,-0.124360,-0.134428,-0.094781,0.271263,0.061070,0.697675,0.102552,0.219925,1.000000,0.786669,0.330917,0.184797,0.134651,0.222821
diaBP,0.051872,0.208283,-0.058059,-0.115955,-0.056746,0.199630,0.055834,0.617734,0.050686,0.174422,0.786669,1.000000,0.385348,0.178744,0.063540,0.150124
BMI,0.073111,0.137511,-0.137555,-0.159821,-0.087395,0.105642,0.036496,0.302949,0.089009,0.121056,0.330917,0.385348,1.000000,0.074131,0.083683,0.082055
heartRate,-0.115285,-0.002722,-0.064214,0.050841,0.064030,0.012889,-0.017019,0.146818,0.060984,0.093053,0.184797,0.178744,0.074131,1.000000,0.097074,0.020514
glucose,0.002940,0.118349,-0.031998,-0.053242,-0.053726,0.054232,0.016061,0.086942,0.614820,0.049884,0.134651,0.063540,0.083683,0.097074,1.000000,0.121990
TenYearCHD,0.091688,0.233983,-0.063279,0.019165,0.052014,0.089152,0.048366,0.181387,0.093431,0.091338,0.222821,0.150124,0.082055,0.020514,0.121990,1.000000

In [120]:
from sklearn.model_selection import train_test_split

x2_train,x2_test,y2_train,y2_test = train_test_split(x2,y2,train_size = 0.8,random_state=42)

In [123]:
from sklearn.linear_model import LogisticRegressionCV

model = LogisticRegressionCV()

model.fit(x2_train,y2_train)

C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1780: FutureWarning: The default value for l1_ratios will change from None to (0.0,) in version 1.10. From version 1.10 onwards, only array-like with values in [0, 1] will be allowed, None will be forbidden. To avoid this warning, explicitly set a value, e.g. l1_ratios=(0,).
  warnings.warn(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1823: FutureWarning: The fitted attributes of LogisticRegressionCV will be simplified in scikit-learn 1.10 to remove redundancy. Set`use_legacy_attributes=False` to enable the new behavior now, or set it to `True` to silence this warning during the transition period while keeping the deprecated behavior for the time being. The default value of use_legacy_attributes will change from True to False in scikit-learn 1.10. See the docstring of LogisticRegressionCV for more details.
  warnings.warn(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\cbec\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegressionCV()

In [125]:
print(f"model score: {model.score(x2_train,y2_train)}")

model score: 0.8550922761449077

In [126]:
print(f"model score: {model.score(x2_test,y2_test)}")

model score: 0.8442622950819673

In [127]:
y2_pred = model.predict(x2_test)

In [129]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y2_test,y2_pred)
print(cm2)

[[609   1]
 [113   9]]

In [131]:
from sklearn.metrics import accuracy_score
accuracy2 = accuracy_score(y2_test,y2_pred)
print(f"accuracy: {accuracy2*100:.2f}%")

accuracy: 84.43%

In [132]:
from sklearn.metrics import precision_score
precision2 = precision_score(y2_test,y2_pred)
print(f"precision: {precision *100:.2f}%")

precision: 100.00%

In [133]:
from sklearn.metrics import recall_score
recall2  = recall_score(y2_test,y2_pred)
print(f"recall: {recall*100:.2f}%")

recall: 100.00%

In [136]:
from sklearn.metrics import f1_score
f2 = f1_score(y2_test,y2_pred)
print(f"f1 score: {f2 *100:.2f}%")

f1 score: 13.64%

In [142]:
from sklearn.metrics import classification_report
print(classification_report(y2_test,y2_pred))

              precision    recall  f1-score   support

           0       0.84      1.00      0.91       610
           1       0.90      0.07      0.14       122

    accuracy                           0.84       732
   macro avg       0.87      0.54      0.53       732
weighted avg       0.85      0.84      0.78       732